### PR TITLE
Updated add task modal

### PR DESCRIPTION
**Pull request by smconvery**
Hey. Pushing up updated Modal. And I pulled Magdiel's changes before I pushed. 

1.) I updated the filtering in 'My tasks'. Now, it's only being filtered by 'priority' whether it's urgent, snoozed, or something else. So tasks won't get duplicated into different accordion sections.

2.) Updated modal input fields so they are now matching the columns. 

3.) For some reason, material ui dates are formatted in a specific way on input forms -- YYYY-MM-DD. Saw online some other people were having similar issues with this, going to look into this some more. But it seems like this an issue with older version of material. Came up with a temporary, sort of gross, solution using template literals. But I'm going to look into it some more.

### CODE REVIEW

**Comment by gjames5355** [comment]
@smconvery can you clear the console.log statements, fix the three warnings, and then resubmit?

**Comment by gjames5355** [comment]
@smconvery I know you didn't create the warnings, but it's best to try and clear these when we can.

**Comment by smconvery** [comment]
Totally get it. Definitely not best practice to push code with errors popping up. I'll fix those right now.

**Comment by smconvery** [comment]
Hey! Fixed those console warnings. Was mostly just material UI stuff: A grid needing to be a container, so you could apply styling and spacing to it. And a couple of onClick functions were place in the icon instead of the icon button. (that was the one that would cause firefox issues). 

Looked further into the warning that was popping up with the add task Modal. Seems like it might just be an issue with the older version of material UI using 'findDomNode.'

**Comment by gjames5355** [comment]
@smconvery this looks great! I will merge now. FYI I disabled the buttons because this feature is being moved from the pilot to 1.0.

**Comment by smconvery** [comment]
Cool. Sounds good

**Pull request merged**
